### Search for Books by Title
GET http://localhost:8080/api/books/search?title=Pride and Prejudice
Content-Type: application/json

###

### Search Books with Pagination
GET http://localhost:8080/api/books/search?title=Java&page=0&size=2
Content-Type: application/json


### Add a Review for a Book
POST http://localhost:8080/api/books/review
Content-Type: application/json

{
  "bookId": 27556,
  "rating": 4,
  "reviewText": "A magnificent and timeless story."
}

###

### Get Book Details with Reviews and Average Rating
GET http://localhost:8080/api/books/27556
Content-Type: application/json
